spring:
  application:
    name: luanvan
  datasource:
    url: jdbc:mysql://localhost:3306/clone_LV
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#cloudinary:
#  cloud-name: dp0tcvlag
#  api-key: 929913749946788
#  api-secret: _bgXach9hiqwxu9JfU8mPTPhYFo